title: Documentación AhoraFicho.es
description: Aquí encontrarás toda la documentación de usuario necesaria para utilizar la plataforma de AhoraFicho.es
theme: just-the-docs

url: https://documentacion.ahoraficho.es

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
