title: Documentación AhoraFicho.es
description: Aquí encontrarás toda la documentación de usuario necesaria para utilizar la plataforma de AhoraFicho.es
theme: just-the-docs

url: https://documentacion.ahoraficho.es

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.png"

aux_links:
  AhoraFicho: https://www.ahoraficho.es
  Solutions2AZ: https://www.solutions2az.net

# Enable or disable the site search
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: "k"

# For copy button on code
enable_copy_code_button: true

# By default, consuming the theme as a gem leaves mermaid disabled; it is opt-in
mermaid:
  version: "10.1.0"

# Enable or disable heading anchors
heading_anchors: true

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Enable or disable the side/mobile menu globally
nav_enabled: true

# Sort order for navigation links
nav_sort: case_sensitive

# External navigation links
nav_external_links:
  - title: Demo Plan Básico
    url: https://demoplanbasico.ahoraficho.es/Identity/Account/AutoLogin?username=comercial@solutions2az.net&password=Demo@2025
    hide_icon: false

  - title: Demo Completa
    url: https://democompleta.ahoraficho.es/Identity/Account/AutoLogin?username=comercial@solutions2az.net&password=Demo@2025
    hide_icon: false

# Show navigation error report
nav_error_report: true

liquid:
  error_mode: strict
  strict_filters: true

# Back to top link
back_to_top: true
back_to_top_text: "Volver arriba"

footer_content: 'Copyright &copy; 2024-2026. Todos los derechos reservados <a href="https://www.ahoraficho.es">AhoraFicho.es</a> por <a href="https://www.solutions2az.net/">Solutions2AZ</a>.'

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%d %b %Y a las %H:%M"

# Footer "Edit this page on GitHub" link text
gh_edit_link: false

# Color scheme
color_scheme: ahoraficho

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Importante
    color: blue
  new:
    title: Nuevo
    color: green
  note:
    title: Nota
    color: purple
  warning:
    title: Advertencia
    color: red
  tip:
    title: Consejo
    color: green

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

sass:
  quiet_deps: true
  silence_deprecations: ['import']